### ISSUE TITLE
close button bug

### ISSUE THREAD

**Issue by Kentakoong** [kkevinm/iTunes-Discord-RP#35] opened 2020-08-16 12:35 UTC
when I hitted the close app button on macOS I cannot open the app up again
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35761701/90334525-7077bc00-dff8-11ea-8dd4-6c99758c61ca.gif)

**Comment by kkevinm** [comment] 2020-08-16 16:09
I added that in the latest version under request, to make the close button hide the app instead of closing it, but the problem is that to show it again you need to hit the app button in the menu bar (the small blue button in the top bar there). This is exactly why I didn't want to make this change, since it's counterintuitive.

**Comment by wynterthecat** [comment] 2020-08-16 17:24
Perhaps a preference option is in order? It seems we’re stuck between two different breeds of counterintuitive, either accidentally quitting the app every few hours or having to remember the dock icon does nothing. Talking to the couple other people I know who use macs, it was a split opinion as to which was better. If it’s not too difficult to implement, I would say make it an option.

**Comment by wynterthecat** [comment] 2020-08-16 17:31
> when I hitted the close app button on macOS I cannot open the app up again
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35761701/90334525-7077bc00-dff8-11ea-8dd4-6c99758c61ca.gif)

Out of curiosity, are you aware that the app used to completely quit when you would press that button? It would not continue running in the background like many apps, i.e. Pages, do. The reason I asked about changing the behavior in the past was because I would accidentally quit it entirely and need to relaunch it, whereas now I just have to click the little icon up top to show it again. If you want to completely close an app on a Mac, typically you press Command-Q while focused on that app. Otherwise most apps will keep running (some don’t which can throw things off especially when they are background agents with a little front end).

**Comment by kkevinm** [comment] 2020-08-16 17:44
Adding a preference for that sounds like the better idea, should be easy enough.

**Comment by wynterthecat** [comment] 2020-08-16 17:46
Okay, that makes sense. I wonder if putting it behind the Preferences window would be better, or if putting it under "connect automatically" would make more sense since people would see it and try what it does to figure out what's better.

**Comment by kkevinm** [comment] 2020-08-18 08:55
I found out how to make it behave like you'd expect, so hitting the dock icon will show the window again. I just have to test that it doesn't break anything on Windows.

**Comment by kkevinm** [comment] 2020-08-18 09:43
Fixed in [v1.5.6](https://github.com/kkevinm/iTunes-Discord-RP/releases/tag/1.5.6).

**Closed by kkevinm** 2020-08-18 09:43 UTC

**Comment by Kentakoong** [comment] 2020-08-18 12:41
thanks!

**Comment by wynterthecat** [comment] 2020-08-18 20:04
Excellent, thank you so much
