### ISSUE TITLE
[BUG] Please Fix : The Song stayed the same when already at another song (macOS)

### ISSUE THREAD

**Issue by Kentakoong** [kkevinm/iTunes-Discord-RP#38] opened 2020-08-24 12:59 UTC
I'm so tired to connect/disconnect it like every 10 mins because it like freezes so much.
@kkevinm can you do something, It's been bugging me alot thanks. If you can fix it

**Comment by Kentakoong** [comment] 2020-08-24 13:00
The version I'm using is the latest version

**Comment by helenwen8** [comment] 2020-08-24 19:21
I have the same issue, but I am having trouble trying to reproduce it. I think one way to reproduce it is by leaving the Rich Presence running and then letting the computer go to sleep. When I wake up the computer and playing music again, it usually freezes. 

I will update here if I can find a more reliable way of reproducing it

**Comment by kkevinm** [comment] 2020-08-24 19:51
I'm also having related issues, but they seem to happen inconsistently so I can't pin down the problem. Also it only seems to happen when running the .app (but not the .jar file, for example)? Honestly, I have no clue, but something's up for sure.

**Comment by helenwen8** [comment] 2020-08-24 20:28
Tried to do some testing, and it seems that whenever I pause the music for more than 2 mins, unpausing the music would not update the rich presence. I wonder if it might be something like Mac OS automatically disconnects the app for saving resources?

**Comment by Kentakoong** [comment] 2020-08-25 04:13
> Tried to do some testing, and it seems that whenever I pause the music for more than 2 mins, unpausing the music would not update the rich presence. I wonder if it might be something like Mac OS automatically disconnects the app for saving resources? 

Yeah yeah me too

**Comment by Kentakoong** [comment] 2020-08-25 04:14
But mine's not sleeping and it just frozed. Hmmn

**Comment by Kentakoong** [comment] 2020-08-26 12:10
@kkevinm welp. I just opened up the app and I played the first song, It frozed at the first song that I played

**Comment by kkevinm** [comment] 2020-08-26 12:44
Yeah, it seems to be random when it happens. For now try using version 1.5.4, that one shouldn't have issues.

**Comment by kkevinm** [comment] 2020-08-27 20:22
I have the suspect that the culprit could be App Nap: when an application is hidden or behind others, this feature will put it to sleep preventing it from updating the rich presence (I checked in the Activity Monitor and indeed App Nap kicks in shortly after the app is put in the background). I'll see if it's possible to prevent this.

**Comment by Kentakoong** [comment] 2020-08-28 15:23
ok thanks

**Comment by Kentakoong** [comment] 2020-08-28 15:23
yeah
I'm thinking of reverting too

**Comment by EthanG45** [comment] 2020-08-30 05:07
Downgraded to 1.5.4 and can confirm it does not fix the issue.

**Comment by Kentakoong** [comment] 2020-08-30 06:19
> Downgraded to 1.5.4 and can confirm it does not fix the issue.

Oh really. I didn't do it yet cuz trying to test it out and report bugs

**Comment by Kentakoong** [comment] 2020-08-31 11:44
This is my summary of v1.5.6

Bugs **EVERY TIME** that I used it

**Comment by Kentakoong** [comment] 2020-08-31 11:46
imma try the .jar for a few days and report back

**Comment by Kentakoong** [comment] 2020-08-31 11:56
@kkevinm you're right

I use .jar and it just runs smooth as you told me.
Perfect.

**Comment by Kentakoong** [comment] 2020-08-31 12:26
welp. still bugging

hmmm

ahhh

**Comment by kkevinm** [comment] 2020-08-31 19:35
I can suggest trying to disable App Nap and see if that solves the issue. How you do it is open the Terminal.app and paste this line: `defaults write NSGlobalDomain NSAppSleepDisabled -bool YES`, then hit Enter (you may have to restart the computer for the change to take effect). If you want to re-enable it, paste the same line but using `NO` instead of `YES`. If this doesn't work, then I really don't know.

**Comment by Kentakoong** [comment] 2020-09-01 14:30
I've used the jar version in windows+mac

just a few errors sometimes.

the jar is the best to use for now @kkevinm as you told us

**Comment by Kentakoong** [comment] 2020-09-01 14:31
rarely bugged as I say

**Comment by Kentakoong** [comment] 2020-09-02 13:19
yeah

ill try the app later this night

**Comment by Kentakoong** [comment] 2020-09-05 05:27
@kkevinm as i tried it for 2 days, i have not found any freezes
I disabled the app nap and it works

**Comment by kkevinm** [comment] 2020-09-05 08:52
Ah all right, that's what I thought. I'll see if it can be fixed without having to do that, but meanwhile I'll add that to the FAQ.

**Comment by kkevinm** [comment] 2020-09-21 16:52
Okay so I've tested it quite extensively and it seems like disabling App Nap does indeed make the app work as intended. For now I'll close this, since it's technically solved, but I'll see if there's a way to prevent it without having to disable App Nap.

**Closed by kkevinm** 2020-09-21 16:52 UTC
